auth:
  adminUser: admin
  adminPassword: admin
externalDatabase:
  host: postgres-keycloak-service
  port: 5432
  user: mendix
  password: mendix
  database: keycloak
service:
  type: NodePort
  ports:
    http: 8080
    https: 8443
  nodePorts:
    http: 32000
    https: 32043
postgresql:
  enabled: false
keycloakConfigCli:
  enabled: true
  command:
  - java
  - -jar
  - /opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar
  - --import.files.locations=/opt/bitnami/keycloak/imports/*.json
  extraVolumeMounts:
  - name: keycloak-imports
    mountPath: /opt/bitnami/keycloak/imports
  extraVolumes:
  - name: keycloak-imports
    configMap:
      name: keycloak-config-cli-import
  initContainers:
  - name: init-keycloak
    image: busybox:1.28
    command: ['sh', '-c', "until nc -z -w 2 keycloak:8080; do echo waiting for keycloak; sleep 5; done"]
initContainers:
- name: init-postgres-keycloak
  image: busybox:1.28
  command: ['sh', '-c', "until nc -z -w 2 postgres-keycloak-service:5432; do echo waiting for postgres; sleep 5; done"]