kind: Service
apiVersion: v1
metadata:
  name: keycloak-service
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 32000
  - name: https
    port: 8443
    nodePort: 32043
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bitnami/keycloak:latest
        env:
        # - name: KEYCLOAK_PRODUCTION
        #   value: "true"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: DB_VENDOR
          value: POSTGRES
        - name: DB_ADDR
          value: postgres-keycloak-service
        - name: DB_DATABASE
          value: keycloak
        - name: DB_USER
          value: mendix
        - name: DB_PASSWORD
          value: mendix
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      initContainers:
      - name: init-postgres-keycloak
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z -w 2 postgres-keycloak-service:5432; do echo waiting for postgres; sleep 5; done"]