apiVersion: v1
kind: Pod
metadata:
  name: keycloak-config-cli
spec:
  containers:
  - name: keycloak-config-cli
    image: bitnami/keycloak-config-cli:latest
    env:
    - name: KEYCLOAK_URL
      value: "http://keycloak-service:8080"
    - name: KEYCLOAK_USER
      value: "admin"
    - name: KEYCLOAK_PASSWORD
      value: "admin"
    - name: KEYCLOAK_LOGIN_REALM
      value: "master"
    - name: IMPORT_FILES_LOCATIONS
      value: "/opt/bitnami/keycloak-config-cli/import/*.json"
    # Mount the config map
    volumeMounts:
    - name: keycloak-config-cli-import
      mountPath: /opt/bitnami/keycloak-config-cli/import
  restartPolicy: Never
  volumes:
  - name: keycloak-config-cli-import
    configMap:
      name: keycloak-config-cli-import
  initContainers:
  - name: init-keycloak
    image: busybox:1.28
    command: ['sh', '-c', "until nc -z -w 2 keycloak-service:8080; do echo waiting for keycloak; sleep 5; done"]